### ISSUE TITLE
Destiny 2 Incorrect Rotation

### ISSUE THREAD

**Issue by beaurancourt** [KovaaK/SensitivityMatcher#8]
From what I understand, destiny 2 is supposed to operate on the same sensitivity scale that overwatch does. When I plug my overwatch sensitivity into destiny 2, it *feels* right, but the `alt+[` brings me no where near to a 360. Adjusting my sensitivity in destiny to make `alt+[` do a 360 brings me to a sensitivity that's **far** too high.

I suspect something funky is going on with's destiny's interpretation of the script's movement.

**Comment by Areteic** [comment]
There might be some mouse smoothing or any other mouse input processing going on. Had really inconsistent 360s in Borderlands until I turned its mouse smoothing off.

**Comment by KovaaK** [comment]
I just got around to testing this, and it functions properly for me.  I have 4 sensitivity in Destiny 2 (aim smoothing turned off), and using the pre-set for Overwatch at 0.0066 yaw with 4 sensitivity perfectly performs a 360.  Make sure your settings in the sensitivity matcher aren't resulting in dropped inputs - maybe try lowering the frequency, and make sure your move partitions is not greater than half of your horizontal resolution.
