### ISSUE TITLE
Script Not working in Rainbow Six Siege

### ISSUE THREAD

**Issue by DivusJulius** [KovaaK/SensitivityMatcher#9]
Apparently the Script does not work in Rainbow Six Siege. I have tested it with CSGO and afterwards tried it in Rainbow Six Siege aswell. I have tried running it as administrator and running it with the AntiCheat Battleye disabled. What reasons could there be for this behaviour?

**Comment by KovaaK** [comment]
Users who have had this issue and resolved it reported that they had to enable raw input and make sure no other action was bound to the "[" key.
